.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MTGWALLPAPER" "1" "June 2017" "Vítor Galvão" "mtgwallpaper"
.
.SH "NAME"
\fBmtgwallpaper\fR \- download Magic: The Gathering wallpapers
.
.SH "SYNOPSIS"
\fBmtgwallpaper [options]\fR
.
.SH "DESCRIPTION"
Download the latest official Magic: The Gathering wallpapers\. Only the ones you don‘t yet have will be downloaded, and only up to a certain number\.
.
.P
A settings file is mandatory, but \fB\-\-init\fR will create an annotated one that should be enough for most people\.
.
.SH "OPTIONS"
.
.TP
\fB\-i, \-\-init\fR
Create a settings file with sensible defaults (overwrites any existing one) and exit\.
.
.TP
\fB\-e, \-\-edit\fR
Open the configuration file in a text editor and exit\.
.
.TP
\fB\-d, \-\-download\fR
Get new wallpapers\.
.
.TP
\fB\-h, \-\-help\fR
Show help\.
.
.SH "AUTHORS"
Vítor Galvão (vitorgalvao\.com)
