#!/usr/bin/env ruby

require 'nokogiri'

# usage
if ARGV[0].nil?
  abort "usage: #{File.basename($0)} <path_to_annotations_file>

  The output file will be next to the original.".gsub(%r{^ {2}},'')
end

annot_file = File.absolute_path(ARGV[0])
annot_feed = Nokogiri::XML(File.open(annot_file))

publication_info = annot_feed.at('publication')
book_title = publication_info.at('dc|title').text
book_author = publication_info.at('dc|creator').text
book_publisher = publication_info.at('dc|publisher').text

out_file = File.dirname(annot_file) + "/#{book_title} (annotations).md"

File.open(out_file, 'w') do |f|
  [book_title, book_author, book_publisher].each do |detail|
    f.puts detail if ! detail.empty?
  end
    f.puts '=' * 10
end

annot_feed.css('annotation').each do |annotation|
  fragment_start = annotation.at('fragment').attribute('start').value
  text = annotation.at('text').text.strip

  File.open(out_file, 'a') do |f|
    f.puts "\n#{text}\n\n"
    f.puts "[§](#{fragment_start})"
    f.puts '-' * 10
  end

end
