#!/usr/bin/env ruby

require 'date'
require 'json'
require 'open-uri'
require 'open3'
require 'optparse'
require 'pathname'

# Options
ARGV.push('--help') if ARGV.empty?

options = {}
OptionParser.new do |opt|
  opt.banner = <<~BANNER
    Show analytics information for casks in the main taps.

    Usage:
      #{File.basename($PROGRAM_NAME)} [options] <cask_name>

    Options:
  BANNER

  opt.on('-a', '--no-age', 'Do not show when cask was added (faster output).') { options[:suppress_age] = true }
  opt.on('-h', '--help', 'Show this help.') { puts opt }
end.parse!

# Helpers
def shallow?(repo)
  Open3.capture2(
    'git', '-C', repo.to_path,
    'rev-parse', '--is-shallow-repository'
  ).first.strip == 'true'
end

# Run
ARGV.each do |cask_name|
  cask_path = Pathname(Open3.capture2('brew', '--prefix').first.strip)
              .join('Homebrew/Library/Taps/homebrew')
              .glob("homebrew-cask*/Casks/#{cask_name}.rb").first

  abort 'Did not find any cask locally named ' + cask_name if cask_path.nil?

  puts cask_name

  analytics_dir = Pathname('/tmp').join('cask-analytics')
  analytics_dir.mkpath

  %w[30 90 365].each do |days|
    json_file = analytics_dir.join("#{days}d.json")

    unless json_file.exist?
      json_file.write(URI.parse(
        "https://formulae.brew.sh/api/analytics/cask-install/#{days}d.json"
      ).read)
    end

    analytics = JSON.parse(json_file.read)['items']
    cask_info = analytics.select { |hash| hash['cask'] == cask_name }.first

    print "#{days} days: "

    if cask_info.nil?
      puts 'n/a'
    else
      puts "#{cask_info['count']} (##{cask_info['number']})"
    end
  end

  cask_tap_dir = cask_path.dirname.dirname

  unless options[:suppress_age]
    if shallow?(cask_tap_dir)
      system('git', '-C', cask_tap_dir, 'fetch', '--unshallow')
    end

    cask_added_date = Date.parse(
      Open3.capture2(
        'git', '-C', cask_tap_dir.to_path,
        'log', '--diff-filter=A',
        '--max-count=1', '--format=%aI', cask_path.to_path
      ).first.strip
    )

    cask_added_formatted = cask_added_date.strftime('%Y, %B %d')
    cask_age = (Date.today - cask_added_date).to_i.to_s

    puts "Age: #{cask_age} days (added #{cask_added_formatted})"
  end

  puts # Empty line to separate multiple casks
end
