#!/bin/bash

# Instructions (shown if no argument is given)
usage() {
echo "usage:

You can either use this to check/audit altered casks by issuing
$0 /path/to/a-cask.rb /path/to/another-cask.rb

Or create (and audit) new ones by doing
$0 --new cask-name abother-cask-name"
}

if [[ -z ${1} ]]; then
	$(usage)
	exit 1
fi

# Default location of the casktapdir
caskroom="/opt/homebrew-cask/Caskroom"
casktapdir="$(brew --prefix)/Library/Taps/phinze-cask"

# If called with the '--new' option, copy a base file for editing
if [[ ${1} == "--uninstall" ]]; then
	brew cask uninstall $(ls "${caskroom}")
	rm -r ${caskroom}/*
elif [[ ${1} == "--new" ]]; then
	shift
	for cask in $@; do
		cp "${casktapdir}/Casks/Acorn.rb" "${cask}.rb"
		vim -c "nmap <space> /'<cr>nci'" -c "normal wcW" "${cask}.rb"
		# After creating casks, audit them with the script
		$0 ${cask}.rb
	done
else
	# Edit the casks
	vim $@
	# Copy casks to the casktapdir and audit them
	for caskfile in $@; do
		cask=$(echo $(basename "${caskfile}") | sed 's/\.rb$//')
		cp "${caskfile}" "${casktapdir}/Casks/"
		brew cask audit "${cask}"
		# Install (and remove after) to see if everything is really working
		brew cask install "${cask}"
	done
	# Revert the casktapdir to its original state
	git --git-dir="${casktapdir}/.git/" --work-tree="${casktapdir}" reset HEAD --hard
fi

exit 0
