#!/bin/bash

# Instructions (shown if no argument is given)
usage() {
echo "usage:

You can either use this to audit altered casks by issuing
$0 a-cask another-cask

Or create (and audit) new ones by doing
$0 --new a-cask another-cask"
}

if [[ -z ${1} ]]; then
  usage
  exit 1
fi

# Location of the casktapdir
casktapdir="$(brew --prefix)/Library/Taps/phinze-cask"

# If called with the '--new' option, create new casks for editing
if [[ ${1} == "--new" ]]; then
  shift
  for cask in $@; do
    brew cask create "${cask}"
    vim -c "nmap <space> /'<cr>nci'" -c "normal wcW" "${cask}.rb"
  done
  # After creating casks, audit them with the script
  $0 $@
else
  cp $@ "${casktapdir}/Casks/"
  brew cask audit --download $@
fi

# Revert the casktapdir to its original state
git --git-dir="${casktapdir}/.git/" --work-tree="${casktapdir}" clean --force
git --git-dir="${casktapdir}/.git/" --work-tree="${casktapdir}" reset HEAD --hard

exit 0
