#!/bin/bash

# Instructions on how to use the script (activated if no arguments are given)
# ---------------------------------------------------------------------------
usage() {
echo "usage: cttsu <object_id> <desired_url>"
}

if [[ -z ${1} ]]; then
	usage
	exit 1
fi

# Arguments to be used
# --------------------
object_id=${1}
desired_url=${2}

# is.gd does not allow the url to be longer than 30 characters
# ------------------------------------------------------------
if [[ ${#desired_url} -ge 30 ]]; then
	echo -e "\n$(tput setaf 1)Short URLs must be a maximum of 30 characters long.$(tput sgr0)\n"
	exit 1
fi

# Check if desired short url is available, and if not, ask for a different one
# ----------------------------------------------------------------------------
short_url_is_available="False"
while [[ ${short_url_is_available} == "False" ]]; do
	is_available=$(curl --silent http://is.gd/forward.php?shorturl=${desired_url})
	if [[ ${is_available} != "" ]]; then
		short_url_is_available="True"
	else
		echo -e "\n$(tput setaf 1)That short URL is already taken, please pick another one.$(tput sgr0)\n"
		exit 1
	fi
done

# Get URL for object on CTT's website
# and use perl to encode the URL, so it can be used with is.gd
# Then get the short URL
# ------------------------------------------------------------
ctt_url=$(echo "http://www.ctt.pt/feapl_2/app/open/objectSearch/cttObjectSearch.jspx?objects=&pesqObjecto.objectoId=${object_id}&showResults=true" | perl -MURI::Escape -lne 'print uri_escape($_)')

short_url=$(curl --silent "http://is.gd/create.php?format=simple&url=${ctt_url}&shorturl=${desired_url}")

# Copy the short URL to the clipboard and print a success message
# ---------------------------------------------------------------
echo ${short_url} | pbcopy
echo -e "\n$(tput setaf 2)The short URL was copied to the clipboard.$(tput sgr0)\n"