#!/bin/bash

readonly program="$(basename "$0")"

syntax_error() {
  echo "$program: $1" >&2
  echo "Try \`$program --help\` for more information." >&2
  exit 1
}

# instructions
usage() {
echo "usage: $program [-h] [-i <file>] [-b <bundleID>]

options:
  -h, --help                           Show this message
  -i <file>, --icon <file>             Set the icon
  -b <bundleID>, --bundle <bundleID>   Set the bundle id"
}

# set options
while [[ "$1" ]]; do
  case "$1" in
    -h | --help)
      usage
      exit 0
      ;;
    -i | --icon)
      icon="$2"
      shift
      ;;
    -b | --bundle)
      id="$2"
      shift
      ;;
    -*)
      syntax_error "unrecognized option: $1"
      ;;
  esac
  shift
done

# stop executing if an option is missing
if [[ -z "${icon}" ]] || [[ -z "${id}" ]]; then usage && exit 1; fi

# set variables
tn_version="$(curl --silent 'https://github.com/alloy/terminal-notifier/releases.atom' | grep '<title>' | sed -n 2p | perl -pe 's|.*<title>(.*)</title>.*|\1|')"
tmp_dir="/tmp/terminal-notifier$RANDOM"
app="${tmp_dir}/terminal-notifier-${tn_version}/terminal-notifier.app"
mkdir "${tmp_dir}"

# get terminal notifier
curl "https://github.com/alloy/terminal-notifier/releases/download/${tn_version}/terminal-notifier-${tn_version}.zip" -Lo "${tmp_dir}/terminal-notifier.zip"
unzip "${tmp_dir}/terminal-notifier.zip" -d "${tmp_dir}"

# set icon and bundle id
cp "${icon}" "${app}/Contents/Resources/Terminal.icns"
sed -i '' "s/nl.superalloy.oss.terminal-notifier/${id}/" "${app}/Contents/Info.plist"

# move it to your Desktop
mv "${app}" "${HOME}/Desktop/"
