#!/bin/bash

readonly program="$(basename "${0}")"

syntax_error() {
  echo "${program}: ${1}" >&2
  echo "Try \`${program} --help\` for more information." >&2
  exit 1
}

# instructions
usage() {
  echo "
    usage: ${program} -i <file> -b <bundle_id>

    options:
      -i <file>, --icon <file>               Set the icon (can be either an 'icns' or an image format, like 'png')
      -b <bundle_id>, --bundle <bundle_id>   Set the bundle id
      -h, --help                             Show this message
  " | sed -E 's/^ {4}//'
}

# set options
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -i | --icon)
      icon="${2}"
      shift
      ;;
    -b | --bundle)
      id="${2}"
      shift
      ;;
    -*)
      syntax_error "unrecognized option: ${1}"
      ;;
  esac
  shift
done

function make_icns() {
  local file="${1}"
  local iconset="$(mktemp -d)"
  local output_icon="$(mktemp).icns"

  if [[ "$(sips --getProperty hasAlpha "${file}" | awk 'END{print $2}')" == 'no' ]]; then
    echo 'Image needs to have an alpha channel'
    exit 1
  fi

  sips --resampleHeightWidth 16 16 "${file}" --out "${iconset}/icon_16x16.png" &> /dev/null
  sips --resampleHeightWidth 32 32 "${file}" --out "${iconset}/icon_16x16@2x.png" &> /dev/null
  sips --resampleHeightWidth 32 32 "${file}" --out "${iconset}/icon_32x32.png" &> /dev/null
  sips --resampleHeightWidth 64 64 "${file}" --out "${iconset}/icon_32x32@2x.png" &> /dev/null
  sips --resampleHeightWidth 128 128 "${file}" --out "${iconset}/icon_128x128.png" &> /dev/null
  sips --resampleHeightWidth 256 256 "${file}" --out "${iconset}/icon_128x128@2x.png" &> /dev/null
  sips --resampleHeightWidth 256 256 "${file}" --out "${iconset}/icon_256x256.png" &> /dev/null
  sips --resampleHeightWidth 512 512 "${file}" --out "${iconset}/icon_256x256@2x.png" &> /dev/null
  sips --resampleHeightWidth 512 512 "${file}" --out "${iconset}/icon_512x512.png" &> /dev/null
  sips --resampleHeightWidth 1024 1024 "${file}" --out "${iconset}/icon_512x512@2x.png" &> /dev/null

  mv "${iconset}" "${iconset}.iconset"
  iconutil --convert icns "${iconset}.iconset" --output "${output_icon}"

  echo "${output_icon}" # so its path is returned when the function ends
}

# stop executing if an option is missing
if [[ -z "${icon}" ]] || [[ -z "${id}" ]]; then usage && exit 1; fi

# set variables
tn_version="$(curl --location --silent 'https://github.com/alloy/terminal-notifier/releases.atom' | grep '<title>' | sed -n 2p | sed -E 's|.*<title>(.*)</title>.*|\1|')"
tmp_dir="$(mktemp -d -t 'terminal-notifier')"
app="${tmp_dir}/terminal-notifier-${tn_version}/terminal-notifier.app"

# get terminal notifier
curl --progress-bar --location "https://github.com/alloy/terminal-notifier/releases/download/${tn_version}/terminal-notifier-${tn_version}.zip" | ditto -xk - "${tmp_dir}"

# set icon and bundle id
[[ "${icon}" != *'.icns' ]] && icon=$(make_icns "${icon}") # convert icon, if not already 'icns'
cp "${icon}" "${app}/Contents/Resources/Terminal.icns"
sed -i '' "s/nl.superalloy.oss.terminal-notifier/${id}/" "${app}/Contents/Info.plist"

# move it to the Desktop
mv "${app}" "${HOME}/Desktop"
