#!/bin/bash

# instructions
usage() {
echo "usage: $0 [-h] [-i] [-d]

options:
	-h Show this message
	-i Set the icon
	-b Set the bundle id"
}

# set options
while getopts hi:b: OPTION
do
	case "${OPTION}"
	in
		h) usage; exit 1;;
		i) icon=${OPTARG};;
		b) id=${OPTARG};;
	esac
done
shift $((OPTIND-1))

# stop executing if an option is missing
if [[ -z "${icon}" ]] || [[ -z "${id}" ]]; then usage && exit 1; fi

# set variables
tmVersion="1.5.0"
tmpDir="/tmp/terminal-notifier$RANDOM"
app="${tmpDir}/terminal-notifier-${tmVersion}/terminal-notifier.app"
mkdir "${tmpDir}"

# get terminal notifier
curl "https://github.com/alloy/terminal-notifier/releases/download/${tmVersion}/terminal-notifier-${tmVersion}.zip" -Lo "${tmpDir}/terminal-notifier.zip"
unzip "${tmpDir}/terminal-notifier.zip" -d "${tmpDir}"

# set icon and bundle id
cp "${icon}" "${app}/Contents/Resources/Terminal.icns"
sed -i '' "s/nl.superalloy.oss.terminal-notifier/${id}/" "${app}/Contents/Info.plist"

# move it to your Desktop
mv "${app}" "${HOME}/Desktop/"
