#!/bin/bash

readonly program="$(basename "${0}")"

function get_output_path {
  local -r force="${1}"
  local -r ext="${2}"
  local -r input_path="${3}"
  local -r init_output_path="${4}"

  local -r output_path="$(
    if [[ -n "${init_output_path}" ]]; then
      [[ "${init_output_path##*.}" == "${ext}" ]] && echo "${init_output_path}" || echo "${init_output_path}${ext}"
    else
      echo "$(pwd -P)/$(basename "${input_path%.*}${ext}")"
    fi
  )"

  echo "${output_path}"

  if [[ "${force}" == 'true' ]]; then
    mkdir -p "$(dirname "${output_path}")"
    return 0
  fi

  if [[ ! -d "$(dirname "${output_path}")" ]]; then
    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
    exit 1
  fi

  if [[ -e "${output_path}" ]]; then
    echo "Cannot write to '${output_path}'. Already exists." >&2
    exit 1
  fi
}

function syntax_error {
  echo -e "${program}: ${1}\nTry \`${program} --help\` for more information." >&2
  exit 1
}

function usage {
  echo "
    Extract app bundle icon as png.

    Usage:
      ${program} [options] <file>

    Options:
      -o, --output-file <file>   File to output to. Default is with same name on current directory.
      -O, --overwrite            Create intermediary directories and overwrite output.
      -h, --help                 Show this message.
  " | sed -E 's/^ {4}//'
}

function get_app_key {
  local -r key="${1}"
  local -r app="${2}"
  local -r plist="${app}/Contents/Info.plist"

  if ! defaults read "${plist}" "${key}" 2> /dev/null; then
    return 1
  fi
}

# available flags
args=()
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -o | --output-file)
      readonly given_output_path="${2}"
      shift
      ;;
    -O | --overwrite)
      readonly overwrite='true'
      ;;
    --)
      shift
      args+=("${@}")
      break
      ;;
    -*)
      syntax_error "Unrecognised option: ${1}"
      ;;
    *)
      args+=("${1}")
      ;;
  esac
  shift
done
set -- "${args[@]}"

readonly input_app="${1}"
readonly output_file="$(get_output_path "${overwrite:-false}" '.png' "${input_app}" "${given_output_path}")"
readonly app_icon_name="$(get_app_key 'CFBundleIconFile' "${input_app}" | sed 's/\.icns$//')"
readonly resources_dir="${input_app}/Contents/Resources"
readonly icns="${resources_dir}/${app_icon_name}.icns"

if [[ "${#}" -ne 1 || ! -d "${input_app}" || "${input_app}" != *'.app' ]]; then
  echo 'An app bundle needs to be given as input' >&2
  usage
  exit 1
fi

if [[ ! -f "${icns}" ]]; then
  echo 'Could not find app icon.' >&2
  exit 1
fi

sips --setProperty format png "${icns}" --out "${output_file}" >/dev/null
