#!/bin/bash

paletteNumber=${1}
apiPalette=http://www.colourlovers.com/api/palette/${paletteNumber}

curl "${apiPalette}" | xmllint --xpath 'string(//palettes/palette/colors)' - | tr -d '\t' | sed '/^$/d' | perl -pe 's/^/#/g;s/\n/, /g' | sed 's/^/color[]palette = { /;s/, $/ };/' | pbcopy