#!/bin/bash

function usage {
  echo "
    Spoof the MAC address

    Usage:
      ${program} run

    The argument 'run' is necessary to prevent running the script by mistake.

    Options:
      -h, --help   Show this help.
  " | sed -E 's/^ {4}//'
}

if [[ "${1}" =~ ^(-h|--help)$ ]]; then
  usage
  exit 0
fi

if [[ "${1}" != 'run' ]]; then
  usage
  exit 1
fi

# Get device and network
readonly wifi_device="$(networksetup -listnetworkserviceorder | grep 'Hardware Port: Wi-Fi' | sed -E 's/.*Device: (.+)\).*/\1/')"
readonly wifi_network="$(networksetup -getairportnetwork "${wifi_device}" | sed 's/.*: //')"

# New random MAC address
sudo /System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport --disassociate
sudo ifconfig "${wifi_device}" ether "$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/./0/2; s/.$//')"
sudo networksetup -detectnewhardware

# Reconnect to network
[[ "${wifi_network}" != *'Wi-Fi power is currently off.' ]] && sudo networksetup -setairportnetwork "${wifi_device}" "${wifi_network}"
