#!/bin/bash

readonly program="$(basename "${0}")"

function get_output_path {
  local -r force="${1}"
  local -r ext="${2}"
  local -r input_path="${3}"
  local -r init_output_path="${4}"

  local -r output_path="$(
    if [[ -n "${init_output_path}" ]]; then
      [[ "${init_output_path##*.}" == "${ext}" ]] && echo "${init_output_path}" || echo "${init_output_path}${ext}"
    else
      echo "$(pwd -P)/$(basename "${input_path%.*}${ext}")"
    fi
  )"

  echo "${output_path}"

  if [[ "${force}" == 'true' ]]; then
    mkdir -p "$(dirname "${output_path}")"
    return 0
  fi

  if [[ ! -d "$(dirname "${output_path}")" ]]; then
    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
    exit 1
  fi

  if [[ -e "${output_path}" ]]; then
    echo "Cannot write to '${output_path}'. Already exists." >&2
    exit 1
  fi
}

function syntax_error {
  echo -e "${program}: ${1}\nTry \`${program} --help\` for more information." >&2
  exit 1
}

function usage {
  echo "
    Make an icns file from a png.

    Usage:
      ${program} [options] <file>

    Options:
      -o, --output-file <file>   File to output to. Default is with same name on current directory.
      -O, --overwrite            Create intermediary directories and overwrite output.
      -h, --help                 Show this message.
  " | sed -E 's/^ {4}//'
}

# available flags
args=()
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -o | --output-file)
      readonly given_output_path="${2}"
      shift
      ;;
    -O | --overwrite)
      readonly overwrite='true'
      ;;
    --)
      shift
      args+=("${@}")
      break
      ;;
    -*)
      syntax_error "Unrecognised option: ${1}"
      ;;
    *)
      args+=("${1}")
      ;;
  esac
  shift
done
set -- "${args[@]}"

readonly input_file="${1}"
readonly output_file="$(get_output_path "${overwrite:-false}" '.icns' "${input_file}" "${given_output_path}")"
readonly iconset="$(mktemp -d)"

if [[ "${#}" -ne 1 || ! -f "${input_file}" ]]; then
  usage
  exit 1
fi

if [[ "$(mdls -raw -name 'kMDItemContentType' "${input_file}")" != 'public.png' ]]; then
  echo 'Image needs to be a png.' >&2
  exit 1
fi

for size in {16,32,64,128,256,512}; do
  sips --resampleHeightWidth "${size}" "${size}" "${input_file}" --out "${iconset}/icon_${size}x${size}.png" &> /dev/null
  sips --resampleHeightWidth "$((size * 2))" "$((size * 2))" "${input_file}" --out "${iconset}/icon_${size}x${size}@2x.png" &> /dev/null
done

mv "${iconset}" "${iconset}.iconset"
iconutil --convert icns "${iconset}.iconset" --output "${output_file}"
