#!/bin/bash

readonly program="$(basename "${0}")"
readonly valid_sizes=('2560x1600' '1920x1080' '1280x960' 'iphone' 'tablet' 'facebook')
readonly default_size="${valid_sizes[0]}"

function is_string_in_array {
  local string="${1}"

  for value in "${@:2}"; do
    [[ "${string}" == "${value}" ]] && return 0
  done

  return 1
}

function usage {
  echo "
    Download Magic: The Gathering wallpapers.

    Usage:
      ${program} [options]

    Options:
      -d, --directory   Directory to save wallpapers to. Defaults to the current one.
      -s, --size        Wallpaper download size. Must be one of: ${valid_sizes[*]}. Defaults to ${default_size}.
      -h, --help        Show this help.
  " | sed -E 's/^ {4}//'
}

# Options
args=()
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -d | --directory)
      readonly given_directory="${2}"
      shift
      ;;
    -s | --size)
      readonly given_wallpaper_size="${2}"
      shift
      ;;
    --)
      shift
      args+=("${@}")
      break
      ;;
    -*)
      echo "Unrecognised option: ${1}"
      exit 1
      ;;
    *)
      args+=("${1}")
      ;;
  esac
  shift
done
set -- "${args[@]}"

# Set wallpaper size to download
readonly wallpaper_size="$(
  if [[ -n "${given_wallpaper_size}" ]]; then
    echo -n "${given_wallpaper_size}"
  else
    echo -n "${default_size}"
  fi
)"

# Abort if wallpaper size is invalid
if ! is_string_in_array "${wallpaper_size}" "${valid_sizes[@]}"; then
  echo "Wallpaper size needs to be one of: ${valid_sizes[*]}" >&2
  exit 1
fi

# Move to download directory
if [[ -n "${given_directory}" && ! -d "${given_directory}" ]]; then
  echo "${given_directory} is not a valid directory." >&2
  exit 1
fi

cd "${given_directory}" || exit 1

# Download wallpapers
readonly wallpaper_urls="$(curl --silent 'https://magic.wizards.com/en/news' | grep --extended-regexp "href=\"//.*?${wallpaper_size}.jpg" | sed -E "s/.*href=\"([^\"]*${wallpaper_size}.jpg)\".*/\1/")"

# Download new wallpapers
for wallpaper_url in ${wallpaper_urls}; do
  echo Downloading "$(basename "${wallpaper_url}")…"
  curl --silent --remote-name "http:${wallpaper_url}"
done
