#!/bin/bash

readonly program="$(basename "${0}")"

# Instructions
function usage {
  echo "
    Backup all bookmarks from a pinboard account.

    Usage:
      ${program} [options]

    'token' options are compatible between pinboard-backup, pinboard-delete-unread, pinboard-link-check, pinboard-url-update, pinboard-waybackmachine

    Options:
      -x, --xml             Export as XML (default is JSON).
      -o, --output <file>   File to export to (defaults to saving in your home).
      -t, --token <token>   Your Pinboard API token.
      -a, --ask-for-token   Ask for your Pinboard API token on start.
      -s, --save-token      Save Pinboard API token to Keychain and exit. Use with '--token' or '--ask-for-token' (macOS-only).
      -h, --help            Show this message.
  " | sed -E 's/^ {4}//'
}

# Options
args=()
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -x | --xml)
      readonly export_format='xml'
      ;;
    -o | --output)
      readonly output_file="${2}"
      shift
      ;;
    -t | --token)
      readonly token="${2}"
      shift
      ;;
    -a | --ask-for-token)
      readonly ask_for_token='true'
      ;;
    -s | --save-token)
      readonly set_keychain_token='true'
      ;;
    --)
      shift
      args+=("${@}")
      break
      ;;
    -*)
      echo "Unrecognised option: ${1}"
      exit 1
      ;;
    *)
      args+=("${1}")
      ;;
  esac
  shift
done
set -- "${args[@]}"

# Defaults for unset variables
[[ -z "${export_format}" ]] && readonly export_format='json'
[[ -z "${output_file}" ]] && readonly output_file="${HOME}/pinboardbackup.${export_format}"

# Ask for api token, if option is set
if [[ -n "${ask_for_token}" ]]; then
  echo 'Please insert your api token (will not be echoed)'
  echo 'You can get it at https://pinboard.in/settings/password'
  read -rsp '> ' token
  echo
fi

# If no token given, look for it in the Keychain
[[ -z "${token}" ]] && readonly token="$(security find-generic-password -s 'Pinboard API Token' -w)"

# Exit if no token was set
if [[ -z "${token}" ]]; then
  echo 'Cannot continue without a Pinboard token.'
  exit 1
fi

# Check if token is correct
if ! curl --fail --silent "https://api.pinboard.in/v1/user/api_token/?auth_token=${token}" > /dev/null; then
  echo "The Pinboard API token appears to be incorrect. Alternatively, Pinboard’s servers might be down." >&2
  exit 1
fi

# Save token to Keychain
if [[ -n "${set_keychain_token}" ]]; then
  security add-generic-password -a "${token%:*}" -s 'Pinboard API Token' -w "${token}"
  exit 0
fi

# Backup
if [[ ! -f "${output_file}" ]]; then
  mkdir -p "$(dirname "${output_file}")"
  touch "${output_file}"
fi

readonly last_update="$(curl --silent "https://api.pinboard.in/v1/posts/update?auth_token=${token}" | grep 'update time' | sed -E 's/.*"(.*)".*/\1/')"

if head -1 "${output_file}" | grep --quiet "${last_update}"; then
  echo 'All bookmarks saved (no change since last backup).'
  exit 0
fi

echo -e "Last saved on: ${last_update}\n" > "${output_file}"
curl --silent "https://api.pinboard.in/v1/posts/all?auth_token=${token}&format=${export_format}" >> "${output_file}"
echo 'All bookmarks saved.'
