#!/bin/bash

readonly program="$(basename "${0}")"

syntax_error() {
  echo "${program}: ${1}" >&2
  echo "Try \`${program} --help\` for more information." >&2
  exit 1
}

# instructions
usage() {
  echo "
    usage: ${program} [options]

    options:
      -t, --token <token>   Your Pinboard API token.
      -a, --ask-for-token   Ask for your Pinboard API token on start.
      -h, --help            Show this message.
      -t, --token <token>     Your Pinboard API token.
      -a, --ask-for-token     Ask for your Pinboard API token on start.
      -s, --save-token        Save Pinboard API token to Keychain and exit. Use with '--token' or '--ask-for-token' (macOS-only, compatible with pinboardwaybackmachine).
      -u, --use-saved-token   Use Pinboard API token in Keychain (macOS-only, compatible with pinboardlinkcheck).
      -h, --help              Show this message.
  " | sed -E 's/^ {4}//'
}

# set options
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -t | --token)
      token="${2}"
      shift
      ;;
    -a | --ask-for-token)
      ask_for_token='true'
      ;;
    -s | --save-token)
      set_keychain_token='true'
      ;;
    -u | --use-saved-token)
      get_keychain_token='true'
      ;;
    -*)
      syntax_error "unrecognized option: ${1}"
      ;;
  esac
  shift
done

# ask for api token, if option is set
if [[ -n "${ask_for_token}" ]]; then
  echo 'Please insert your api token (will not be echoed)'
  echo 'You can get it at https://pinboard.in/settings/password'
  read -sp '> ' token
  echo
fi

# Use saved token (if any)
[[ -n "${get_keychain_token}" ]] && token="$(security find-generic-password -a "${USER}" -s pinboard_api_token -w)"

# exit if no token was set
if [[ -z "${token}" ]]; then
  usage
  exit 1
fi

# Check if token is correct
token_check="$(curl --silent "https://api.pinboard.in/v1/user/api_token/?auth_token=${token}")"
if [[ -z "${token_check}" ]]; then
  echo 'The used Pinboard API token appears to be incorrect. Alternatively, Pinboard’s servers might be down.'
  exit 1
fi

# Save token to Keychain
if [[ -n "${set_keychain_token}" ]]; then
  security add-generic-password -a "${USER}" -s pinboard_api_token -w "${token}"
  exit 0
fi

# get all your pinboard links
links=$(curl --silent "https://api.pinboard.in/v1/posts/all?auth_token=${token}" | grep '^<post' | cut -d '"' -f 2 | sed '1d')
link_countdown="$(wc -l <<< "${links}" | tr -d ' ')"

# check each link individually
for page in ${links} ; do
  echo "[${link_countdown}] Archiving ${page}…"
  ((link_countdown--))

  curl --location --silent --output /dev/null "https://web.archive.org/save/${page}"
done