#!/bin/bash

readonly program="$(basename "${0}")"

function syntax_error {
  echo -e "${program}: ${1}\nTry \`${program} --help\` for more information." >&2
  exit 1
}

function absolute_path {
  local -r relative_path="${1}"

  if [[ -e "${relative_path}" ]]; then
    if [[ -d "${relative_path}" ]]; then
      cd "${relative_path}" || return 1
      pwd -P
    else
      cd "$(dirname "${relative_path}")" || return 1
      echo "$(pwd -P)/$(basename "${1%/}")"
    fi
  else
    echo "${FUNCNAME[0]}: no such file or directory: ${relative_path}" >&2
    return 1
  fi
}

function get_output_path {
  local -r ext="${1}"
  local -r input_path="${2}"
  local output_path="${3}"

  if [[ ! -d "$(dirname "${output_path}")" ]]; then
    echo "Cannot create '${output_path}'. Parent directory does not exist." >&2
    exit 1
  fi

  if [[ -n "${output_path}" ]]; then
    [[ "${output_path##*.}" == "${ext}" ]] && echo "${output_path}" || echo "${output_path}${ext}"
  else
    output_path="$(pwd -P)/$(basename "${input_path%.*}${ext}")"

    while [[ -e "${output_path}" ]]; do
      output_path="${output_path%.*}_$(date -u +'%Y.%m.%d.%H%M%S')${ext}"
    done

    echo "${output_path}"
  fi
}

function usage {
  echo "
    Extract pkg files in a logical hierarchy.

    Usage:
      ${program} [options] <path_to_pkg>

    Options:
      -o, --output-dir <dir>   Directory to extract to. Default is with same name on current directory. Appends '.extracted' to the name.
      -h, --help               Show this message.
  " | sed -E 's/^ {4}//'
}

args=()
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -o | --output-dir)
      readonly given_output_path="${2}"
      shift
      ;;
    --)
      shift
      args+=("${@}")
      break
      ;;
    -*)
      syntax_error "Unrecognized option: ${1}"
      ;;
    *)
      args+=("${1}")
      ;;
  esac
  shift
done
set -- "${args[@]}"

readonly input_pkg="${1}"
readonly extract_dir="$(mktemp -d)/extracted_pkg"
readonly output_dir="$(get_output_path '.extracted' "${input_pkg}" "${given_output_path}")"

if [[ "${#}" -ne 1 || "$(file --brief --mime-type "${input_pkg}")" != 'application/x-xar' ]]; then
  usage
  exit 1
fi

pkgutil --expand "${input_pkg}" "${extract_dir}"

while IFS= read -r -d '' payload; do
  payload_extract_dir="$(mktemp -d)"
  cd "${payload_extract_dir}" || exit 1

  /usr/bin/gzip --decompress --suffix '' --stdout "${payload}" | /usr/bin/cpio -i 2> /dev/null

  cd "$(dirname "${payload}")" || exit 1
  rm "${payload}"
  mv "${payload_extract_dir}" "${payload}"
done < <(find "${extract_dir}" -type f -name 'Payload' -print0)

while IFS= read -r -d '' pkg; do
  mv "${pkg}" "${pkg}.extracted"
done < <(find "${extract_dir}" -type d -name '*.pkg' -print0)

mv "${extract_dir}" "${output_dir}"
