#!/bin/bash

commit_hash_file="/tmp/prfix_hash_save"
issue_number_file="/tmp/issue_number_save"

usage() {
  echo "
  usage: $0 [-h] [-c] <github_pull_request_url>

  Every option should be used on its own, without the others.
    <github_pull_request_url>
      Should be the complete url. Use this first, to apply the pull request as a patch.
    -c [remote]
      Use after making your fixes. If you use it with uncommitted changes, they'll all be squashed (fixup) into the original patch; else your commits will be preserved. Takes an optional remote to push to (defaults to \"origin\").
    -h
      Show this help.
  " | sed -E 's/^ {2}//'
}

apply_patch() {
  url=$(echo "$1" | perl -pe 's/(.*\d).*/\1/') # clean url of extraneous information
  issue_number=$(echo "${url}" | sed 's|.*/||')
  patch_url="${url}.patch" # github pull request url, ending in '.patch'
  branch_name="fix-${issue_number}"

  git checkout -b "${branch_name}"
  curl --silent "${patch_url}" | git am # get and apply patch

  git rev-parse HEAD > "${commit_hash_file}" # save hash from current commit
  echo "${issue_number}" > "${issue_number_file}" # save issue number

  echo "
    Make your necessary changes, and run
      $0 -c

    If you have uncommitted changes, they'll be squashed into the original parch.
    If you have new commits, they’ll be included separately
  " | sed -E 's/^ {2}//'
}

push_changes() {
  original_commit="$(cat ${commit_hash_file})"
  original_issue="#$(cat ${issue_number_file})"
  branch_name="$(git rev-parse --abbrev-ref HEAD)"
  uncommitted_changes="$(git status --porcelain)"

  # squash your fixes into the original patch, if there are uncommitted changes
  if [[ "${uncommitted_changes}" ]]; then
    git commit --all --allow-empty-message --message ''
    git reset --soft "${original_commit}"
    # add message to close the original pull request
    original_commit_message="$(git log --oneline -1 | cat - | sed -E 's/^[^ ]* //')"
    git commit --amend --message "${original_commit_message}" --message "Closes ${original_issue}."
  fi

  # push and delete branch
  git push "${remote}" "${branch_name}"
  git checkout master
  git branch -D "${branch_name}"
}

if [[ "$1" =~ https://github.com/* ]]; then
  apply_patch "$1"
elif [[ "$1" == '-c' ]]; then
  # if called with an argument, use that as the remote to push to; else use 'origin'
  [[ -z "$2" ]] && remote="origin" || remote="$1"
  push_changes
else
  usage
fi
