#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'

def usage
  puts "Usage: #{File.basename($PROGRAM_NAME)} <rtp_play_url> <output_file>"
end

if ARGV[0] !~ %r{^https?://www.rtp.pt/play} || ARGV[1].nil?
  usage
  exit 1
end

if ARGV[0] =~ /(-h|--help)/
  usage
  exit 0
end

cdn = 'http://cdn-ondemand.rtp.pt'
link = ARGV[0]
output_name = ARGV[1]

page = Nokogiri::HTML(URI.open(link))

video_link = cdn + page.css('script:contains("fileKey")').text.split("\n").select { |l| l.match(/^\s*fileKey/) }.join.sub(/.*"(.*)".*/, '\1')
video_ext = File.extname(video_link)

system('curl', '--progress-bar', video_link, '--output', output_name + video_ext)
