#!/bin/bash

readonly program="$(basename "${0}")"

function syntax_error {
  echo "${program}: ${1}" >&2
  echo "Try \`${program} --help\` for more information." >&2
  exit 1
}

IFS=$'\n'

# Instructions on how to use the script
# Shown with '-h', or when no arguments are given
function usage {
  echo "
    usage: \$1 [options] <files>

    options:
      -s <num>, --starting-number <num>   Sets starting number for the sequence (defaults to 1).
      -l <num>, --leading-zeros <num>     Sets the amount of leading zeros (defaults to what'll accomodate the number of files).
      -p <string>, --prepend <string>     Sets name to prepend to the sequence number (defaults to nothing).
      -a <string>, --append <string>      Sets name to append to the sequence number (defaults to nothing).
      -v, --verbose                       Be verbose.
      -h, --help                          Show this message.
  " | sed -E 's/^ {4}//'
}

if [[ "${#}" -eq 0 ]]; then
  usage
  exit 1
fi

# Available flags to use with the script
positional=()
while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -s | --starting-number)
      starting_num="${2}"
      shift
      ;;
    -l | --leading-zeros)
      sequence_length="$(bc <<< "${2} + 1")"
      shift
      ;;
    -p | --prepend)
      string_to_prepend="${2}"
      shift
      ;;
    -a | --append)
      string_to_append="${2}"
      shift
      ;;
    -v | --verbose)
      be_verbose="v"
      ;;
    -*)
      syntax_error "unrecognized option: ${1}"
      ;;
    *)
      positional+=("${1}")
      ;;
  esac
  shift
done
set -- "${positional[@]}"

# Determines the starting number, depending on if one was picked
num="$([[ -n "${starting_num}" ]] && bc <<< "${starting_num} - 1" || echo '0')"

# If no sequence length is given,
# it will be set accordingly to what the last number
# in the sequence is (depending on the starting number)
if [[ -z "${sequence_length}" ]]; then
  sequence_end="$(bc <<< "${#} + ${num}")"
  sequence_length="${#sequence_end}"
fi

# The actual renaming part
for file_to_rename in "${@}"; do
  num="$(printf "%.${sequence_length}d" "$(bc <<< "${num} + 1")")"
  file_extension="$([[ "${file_to_rename}" = *.* ]] && echo ".${file_to_rename##*.}" || echo '')"

  mv -n"${be_verbose}" "${file_to_rename}" "$(dirname "${file_to_rename}")/${string_to_prepend}${num}${string_to_append}${file_extension}"
done
