#!/bin/bash

# Show help
if [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
  echo "This script checks the sunrise and sunset times for a given location (using the Wolfram Alpha API) and sends an email with the information. To set it up, run it with no arguments."

  exit 0
fi

# Prepare configuration
readonly config_dir="${HOME}/.config/suntimes"
readonly config_file="${config_dir}/suntimes.config"
[[ ! -d "$(basename "${config_file}")" ]] && mkdir -p "${config_dir}"

# Make configuration file if it does not exist
if [[ ! -f "${config_file}" ]]; then
  echo "
    api_key='' # Your Wolfram Alpha API key
    cities='' # The cities you want to check times for (comma-separated)
    email='' # Email addresses to send the times to (comma-separated)
    server_sendmail='' # Email address to list as sender
    send_from=\"Suntimes script <\${server_sendmail}>\" # Can be left as is, unless you want to change the sender name
  " | sed '/^\s*$/d' | sed -E 's/^ {4}//' > "${config_file}"

  echo "A configuration file is needed for the script to work. It's prefilled with instrctions at ${config_file}"

  exit 1
fi

# Run the script
source "${config_file}"
readonly details_file="$(mktemp)"
readonly email_contents="$(mktemp)"

OLDIFS="${IFS}"
IFS=','

for city in $(echo "${cities}"); do
  curl --silent "http://api.wolframalpha.com/v2/query?input=sunrise+sunset+${city}&appid=${api_key}" > "${details_file}"
  sunrise="$(grep 'sunrise |' "${details_file}" | tail -1 | sed -E 's/.*\| (.*) \(.*/\1/')"
  sunset="$(grep 'sunset |' "${details_file}" | tail -1 | sed -E 's/.*\| (.*) \(.*/\1/')"
  light_duration="$(grep 'duration of daylight |' "${details_file}" | tail -1 | sed -E 's/.*\| (.*)<.*/\1/')"

  echo "
    ${city}
    Amanhecer: ${sunrise}
    Anoitecer: ${sunset}
    Duração:   ${light_duration}" | sed 's/ *//' >> "${email_contents}"
done

IFS="${OLDIFS}"
sed '/./,$!d' -i'' "${email_contents}" # Remove leading blank lines

mail -r "${send_from}" -s 'Horas do Sol' "${email}" < "${email_contents}"
