#!/bin/bash

read -rn0 -p 'Important: make sure you have your USB flash drive removed.
Press ↩ to continue running the script'

# get ubuntu disk
read -rp 'Set the full path to your Ubuntu iso (you can drop the file on top of this terminal window)
> ' ubuntu_iso

# save list of connected disks
diskutil list > /tmp/diskutillist1
read -rn0 -p 'Insert your USB flash drive now, and after it gets mounted, press ↩'
diskutil list > /tmp/diskutillist2

# get disk to save to
usb_disk=$(diff /tmp/diskutillist1 /tmp/diskutillist2 | grep '> /dev' | sed 's/> //')

# convert the ubuntu iso
ubuntu_dmg="/tmp/ubuntu.dmg"
hdiutil convert -quiet "${ubuntu_iso}" -format UDRW -o "${ubuntu_dmg}"

# write it to the usb disk
diskutil unmountDisk "${usb_disk}"
echo 'Ubuntu will now be saved to your USB flash drive. This should take a while. You may need to enter your password (for the write permissions).'
sudo dd if="${ubuntu_dmg}" of="${usb_disk}" bs=1m

# eject disk
diskutil eject "${usb_disk}"

echo 'Done. You now have a bootable Ubuntu USB flash drive.'
