#!/bin/bash

# calculate which week (batch) unsplash is on
batch=$(echo "$(( ($(date '+%s') - $(date -j -f '%Y-%m-%d' '2013-05-21' '+%s')) / (10 * 24 * 3600) ))")

# set week number with four digits, default download dir
week=$(printf '%.4d' ${batch})
downloadDir="${HOME}/Desktop/unsplash"
num=01

# make download dir if it doesn't exist, and save links to a variable
mkdir -p "${downloadDir}"
links=$(curl 'http://unsplash.com/' | grep 'alt="Download' | perl -pe 's/<a href="(.*?)".*/$1/')

# download the images
for line in $(echo ${links}); do
	curl "${line}" -Lo "${downloadDir}/${week}-${num}.jpg"
	num=$(printf '%.2d' "$((10#${num}+1))")
done
